FROM node:21-slim

RUN yarn set version stable

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install

COPY src ./src
COPY tsconfig.json ./
COPY vite.config.mts ./
COPY index.html ./

EXPOSE 3000

CMD ["yarn", "start"]