FROM node:21-slim

WORKDIR /usr/src/app

COPY package.json yarn.lock .vscode .yarnrc.yml ./

COPY .yarn/ .yarn/

RUN yarn install
RUN yarn dlx @yarnpkg/sdks vscode

COPY src ./src
COPY tsconfig.json ./
COPY vite.config.mts ./
COPY index.html ./

EXPOSE 3000

CMD ["yarn", "start"]