# Build stage
FROM node:21-slim as build

WORKDIR /usr/src/app

# Copy necessary files for installing dependencies
COPY package.json yarn.lock .yarnrc.yml ./

# Copy your yarn offline cache
COPY .yarn/ .yarn/

# Install dependencies
RUN yarn install

# Copy your app source code
COPY src ./src
COPY tsconfig.json ./
COPY vite.config.mts ./
COPY index.html ./
COPY .prettierignore .prettierrc ./

# Build your app
RUN yarn build

# Runtime stage
FROM nginx:alpine

# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy static assets from builder stage
COPY --from=build usr/src/app/dist .

COPY production_config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]