services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  backend:
    build: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "16000:16000"
    environment:
      - FLASK_ENV=development
