services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
      - ./frontend/package.json:/usr/src/app/package.json
      - ./frontend/yarn.lock:/usr/src/app/yarn.lock
      - ./frontend/vite.config.mts:/usr/src/app/vite.config.mts
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "16000:16000"
    environment:
      - FLASK_DEBUG=1