FROM node:20.5

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

RUN yarn add typescript @types/react @types/react-dom -D

RUN yarn add @typescript-eslint/parser @typescript-eslint/eslint-plugin prettier eslint-config-prettier eslint-plugin-prettier -D

COPY . .

CMD ["yarn", "start"]