FROM python:3.10-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN apt-get update && apt-get install -y \
    build-essential \
    libxrender1 \
    libxext6 \
    libfontconfig1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir -r requirements.txt gunicorn

COPY . .

ENV PYTHONPATH=/usr/src/app/app

EXPOSE 16000

# Replace flask run with a production server
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:16000", "app.wsgi:app"]