FROM python:3.11.4-bullseye

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=api.py

EXPOSE 16000

CMD ["flask", "run", "--host=0.0.0.0", "--port=16000"]